#:schema node_modules/wrangler/config-schema.json
name = "videographer"
main = "src/index.ts"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]
routes = [
	{ pattern = "videos.toasted.dev", custom_domain = true }
]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "videographer-db"
database_id = "2d9e8575-eac3-4205-8adb-d26618169344"

[triggers]
crons = ["0 * * * *"]
